name: delivery_time_torch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - pytorch
  - cudatoolkit
  - pip
  - ipykernel

  - pip:
      - hyperopt
      - lime
      - mlflow
