name: delivery_time_torch
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - numba
  - matplotlib
  - seaborn
  - plotly
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - ipykernel
  - pyspark
  - py4j      
  - jedi-language-server
  - pip
  - openjdk
  - nodejs

  - pip:
      - hyperopt
      - lime
      - mlflow
      - nbformat
      - kaleido
      - torchsummary
      - jupyterlab
