artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/de60554cbab8492aa577fa5fedc6226b/artifacts
end_time: 1718791324202
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: de60554cbab8492aa577fa5fedc6226b
run_name: bald-stag-418
run_uuid: de60554cbab8492aa577fa5fedc6226b
source_name: ''
source_type: 4
source_version: ''
start_time: 1718791207415
status: 3
tags: []
user_id: Bharat Khanna
