artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/a2cf766a0ec04e2e88dadbe6b39fd591/artifacts
end_time: 1718788090647
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: a2cf766a0ec04e2e88dadbe6b39fd591
run_name: industrious-pug-19
run_uuid: a2cf766a0ec04e2e88dadbe6b39fd591
source_name: ''
source_type: 4
source_version: ''
start_time: 1718787813247
status: 3
tags: []
user_id: Bharat Khanna
