artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/84fdec684c64461b846f0a9c8302b84e/artifacts
end_time: 1718788936567
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: 84fdec684c64461b846f0a9c8302b84e
run_name: powerful-jay-916
run_uuid: 84fdec684c64461b846f0a9c8302b84e
source_name: ''
source_type: 4
source_version: ''
start_time: 1718788656663
status: 3
tags: []
user_id: Bharat Khanna
