artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/edf12e4e0b614dcd954db55d1347289b/artifacts
end_time: 1718796414615
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: edf12e4e0b614dcd954db55d1347289b
run_name: nebulous-mole-467
run_uuid: edf12e4e0b614dcd954db55d1347289b
source_name: ''
source_type: 4
source_version: ''
start_time: 1718796282007
status: 3
tags: []
user_id: Bharat Khanna
