artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/ec21533553b74e01b9407e29a348ccfb/artifacts
end_time: 1718790146860
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: ec21533553b74e01b9407e29a348ccfb
run_name: upbeat-whale-376
run_uuid: ec21533553b74e01b9407e29a348ccfb
source_name: ''
source_type: 4
source_version: ''
start_time: 1718789990886
status: 3
tags: []
user_id: Bharat Khanna
