artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/caa9f70e73cd43378b37f2f548e7f91c/artifacts
end_time: 1718795866078
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: caa9f70e73cd43378b37f2f548e7f91c
run_name: enthused-ant-140
run_uuid: caa9f70e73cd43378b37f2f548e7f91c
source_name: ''
source_type: 4
source_version: ''
start_time: 1718795865978
status: 4
tags: []
user_id: Bharat Khanna
