artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/993373217101926689/f3dc68f7211c4a588effaee815a4c958/artifacts
end_time: 1718787541168
entry_point_name: ''
experiment_id: '993373217101926689'
lifecycle_stage: active
run_id: f3dc68f7211c4a588effaee815a4c958
run_name: defiant-worm-810
run_uuid: f3dc68f7211c4a588effaee815a4c958
source_name: ''
source_type: 4
source_version: ''
start_time: 1718787397063
status: 3
tags: []
user_id: Bharat Khanna
