artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/f614e2a0361840f494aa2a0da6431ef2/artifacts
end_time: 1718796104809
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: f614e2a0361840f494aa2a0da6431ef2
run_name: clean-dog-220
run_uuid: f614e2a0361840f494aa2a0da6431ef2
source_name: ''
source_type: 4
source_version: ''
start_time: 1718796087027
status: 3
tags: []
user_id: Bharat Khanna
