artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/77bc9bf27f624490ac473b0b12fbc5b3/artifacts
end_time: 1718794092081
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: 77bc9bf27f624490ac473b0b12fbc5b3
run_name: glamorous-smelt-395
run_uuid: 77bc9bf27f624490ac473b0b12fbc5b3
source_name: ''
source_type: 4
source_version: ''
start_time: 1718792950788
status: 3
tags: []
user_id: Bharat Khanna
