artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/91ac8f74618d4d0898081d99dfdd8b32/artifacts
end_time: 1718789313021
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: 91ac8f74618d4d0898081d99dfdd8b32
run_name: delicate-donkey-369
run_uuid: 91ac8f74618d4d0898081d99dfdd8b32
source_name: ''
source_type: 4
source_version: ''
start_time: 1718789150247
status: 3
tags: []
user_id: Bharat Khanna
