artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/69e6dda6713845939c8b9c280aba77a7/artifacts
end_time: 1718789036037
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: 69e6dda6713845939c8b9c280aba77a7
run_name: flawless-loon-257
run_uuid: 69e6dda6713845939c8b9c280aba77a7
source_name: ''
source_type: 4
source_version: ''
start_time: 1718788936578
status: 3
tags: []
user_id: Bharat Khanna
