artifact_location: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/993373217101926689
creation_time: 1718787397050
experiment_id: '993373217101926689'
last_update_time: 1718787397050
lifecycle_stage: active
name: Enhanced NN
