artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/de70df61eb5548de9b2847c90bda9277/artifacts
end_time: 1718796231939
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: de70df61eb5548de9b2847c90bda9277
run_name: legendary-shrike-71
run_uuid: de70df61eb5548de9b2847c90bda9277
source_name: ''
source_type: 4
source_version: ''
start_time: 1718796140456
status: 3
tags: []
user_id: Bharat Khanna
