artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/e21ac85afd4a43b487b51aca70c3d847/artifacts
end_time: 1718787813232
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: e21ac85afd4a43b487b51aca70c3d847
run_name: nosy-hawk-768
run_uuid: e21ac85afd4a43b487b51aca70c3d847
source_name: ''
source_type: 4
source_version: ''
start_time: 1718787698429
status: 3
tags: []
user_id: Bharat Khanna
