artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/633ec64b0eb34648b5ef8ecbcbeb1ae5/artifacts
end_time: 1718792662398
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: 633ec64b0eb34648b5ef8ecbcbeb1ae5
run_name: capricious-sloth-420
run_uuid: 633ec64b0eb34648b5ef8ecbcbeb1ae5
source_name: ''
source_type: 4
source_version: ''
start_time: 1718792662352
status: 4
tags: []
user_id: Bharat Khanna
