artifact_location: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/368551665169468693
creation_time: 1718787369830
experiment_id: '368551665169468693'
last_update_time: 1718787369830
lifecycle_stage: active
name: Simple NN
