artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/aa06417ff52749a3ba2802dfada22559/artifacts
end_time: 1718790845250
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: aa06417ff52749a3ba2802dfada22559
run_name: upbeat-squirrel-527
run_uuid: aa06417ff52749a3ba2802dfada22559
source_name: ''
source_type: 4
source_version: ''
start_time: 1718790554562
status: 3
tags: []
user_id: Bharat Khanna
