artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/3d28648d62264acd837df9c2d2b90d60/artifacts
end_time: 1718796016155
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: 3d28648d62264acd837df9c2d2b90d60
run_name: judicious-conch-811
run_uuid: 3d28648d62264acd837df9c2d2b90d60
source_name: ''
source_type: 4
source_version: ''
start_time: 1718796011278
status: 4
tags: []
user_id: Bharat Khanna
