artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/d3601d0171724b1f9fe6ebcda62704f9/artifacts
end_time: 1718791092000
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: d3601d0171724b1f9fe6ebcda62704f9
run_name: serious-moth-50
run_uuid: d3601d0171724b1f9fe6ebcda62704f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1718790938290
status: 3
tags: []
user_id: Bharat Khanna
