artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/f0be5694e56e46beab7b2aa2418d8837/artifacts
end_time: 1718788378031
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: f0be5694e56e46beab7b2aa2418d8837
run_name: abundant-rook-87
run_uuid: f0be5694e56e46beab7b2aa2418d8837
source_name: ''
source_type: 4
source_version: ''
start_time: 1718788090663
status: 3
tags: []
user_id: Bharat Khanna
