artifact_location: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819
creation_time: 1718787541671
experiment_id: '322771809794979819'
last_update_time: 1718787541671
lifecycle_stage: active
name: Model HyperParam Optimization
