artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/d388193a1ed4413daac0df1a03859398/artifacts
end_time: 1718792713253
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: d388193a1ed4413daac0df1a03859398
run_name: persistent-mare-637
run_uuid: d388193a1ed4413daac0df1a03859398
source_name: ''
source_type: 4
source_version: ''
start_time: 1718792713136
status: 4
tags: []
user_id: Bharat Khanna
