artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/240f2d9a0e04486c90b3458dedf286fb/artifacts
end_time: 1718789709575
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: 240f2d9a0e04486c90b3458dedf286fb
run_name: bittersweet-elk-719
run_uuid: 240f2d9a0e04486c90b3458dedf286fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1718789551068
status: 3
tags: []
user_id: Bharat Khanna
