artifact_location: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485
creation_time: 1718792662339
experiment_id: '165477233607370485'
last_update_time: 1718792662339
lifecycle_stage: active
name: Optimized Final Model
