artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/9c1abc5c69114d1c935e8573052b5dcc/artifacts
end_time: 1718792682443
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: 9c1abc5c69114d1c935e8573052b5dcc
run_name: debonair-bat-166
run_uuid: 9c1abc5c69114d1c935e8573052b5dcc
source_name: ''
source_type: 4
source_version: ''
start_time: 1718792682336
status: 4
tags: []
user_id: Bharat Khanna
