artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/165477233607370485/dfaae1e7426740fbb6fb92b6aee0fbd4/artifacts
end_time: 1718795653349
entry_point_name: ''
experiment_id: '165477233607370485'
lifecycle_stage: active
run_id: dfaae1e7426740fbb6fb92b6aee0fbd4
run_name: hilarious-shrike-769
run_uuid: dfaae1e7426740fbb6fb92b6aee0fbd4
source_name: ''
source_type: 4
source_version: ''
start_time: 1718795592301
status: 3
tags: []
user_id: Bharat Khanna
