artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/b53a107dd72e4a7ab74a213628a68c56/artifacts
end_time: 1718789551052
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: b53a107dd72e4a7ab74a213628a68c56
run_name: brawny-eel-877
run_uuid: b53a107dd72e4a7ab74a213628a68c56
source_name: ''
source_type: 4
source_version: ''
start_time: 1718789436603
status: 3
tags: []
user_id: Bharat Khanna
