artifact_uri: file:///C:/Users/Bharat Khanna/OneDrive/Scaler/Projects/delivery_estimation_nn/delivery_time_nn/notebook/../mlruns/322771809794979819/5672f1c62dcb4b5a880513f454801feb/artifacts
end_time: 1718790938271
entry_point_name: ''
experiment_id: '322771809794979819'
lifecycle_stage: active
run_id: 5672f1c62dcb4b5a880513f454801feb
run_name: amazing-goat-325
run_uuid: 5672f1c62dcb4b5a880513f454801feb
source_name: ''
source_type: 4
source_version: ''
start_time: 1718790845264
status: 3
tags: []
user_id: Bharat Khanna
